apache/incubator-ponymail-foal

- tools/migrate.py
This PR fixes a bug where `migrate.py` would not migrate all documents. The problem is that in the loop iterating over all documents in the source database, documents are appended gradually into a buffer. When the buffer size exceeds 100, the whole buffer is bulk pushed and then cleared. This leads to a "leftovers" problem if the number of source document is not an exact multiple of 100, meaning that up to 99 documents may be left in the buffer after the final loop and never pushed because the buffer size did not exceed 100.
The fix suggested in this PR is to add an extra check after the loop, bulk pushing the buffer again if the buffer size is greater than 0. The problem only exists for the mbox and source indices; attachments are handled one-by-one, and have no buffer.
> Ensure that all docs are migrated

- server/plugins/background.py
Foal does not correctly discover all lists available to it from its Elasticsearch database because the underlying aggregation query does not specify a size, and so the default of ten is used. This means that Foal will only ever discover up to ten available mailing lists.
Unfortunately it is not possible to fix this by specifying `size=0` as in other Elasticsearch queries to receive unbounded results. If you try this for a term aggregation you get a error along the lines of:
```
elasticsearch.exceptions.RequestError:
RequestError(400, 'x_content_parse_exception', '[1:114] [terms] failed to parse field [size]')
```
Therefore this PR raises the limit to `8192` mailing lists, meaning that at most `8192` mailing lists will be correctly discovered. This number was chosen arbitrarily.
> Increase the number of lists returned during term aggregation

- tools/setup.py
When `setup.py` was switched to `dburl` some old references to `hostname` and `port` were not updated, causing the script to fail when run. This PR fixes that.
> Fix configuration generation template strings

- server/endpoints/source.py
This PR fixes a small bug in the source endpoint. The `mid` field was being used to retrieve a source document, which was correct for Ponymail but in Foal the `dbid` field is used instead.
> Use dbid instead of mid to get source

- server/endpoints/preferences.py
- server/plugins/configuration.py
- server/plugins/session.py
When hosting Foal across multiple domains or subdomains it may be desirable to show only the mailing lists for the current domain or subdomain in the user interface. This PR adds a boolean configuration option called `ui.focus_domain`, set to `False` by default, which when set to `True` implements this functionality.
> Add focus_domain preference to restrict lists to the current domain

- webui/list.html
The "Static HTML lists" link is broken due to `xlist` not being defined. Most likely it should be `current_list + '@' + current_domain`. In any case, the link is broken even with this fix because `/api/static.lua/list@example.org` returns "API Endpoint not found!". This PR therefore fixes the JS but also comments out the link, ready for uncommenting when the static list API is ported.
> Fix static lists JS and comment out

- tools/__init__.py
- tools/archiver.py
- tools/import-mbox.py
- tools/migrate.py
- tools/plugins/elastic.py
- tools/plugins/generators.py
- tools/push-failures.py
The Python files in the `tools` directory are written to be run as scripts from that directory. This means that the `archiver.py` file doesn't work when installed as a package, which its own documentation advises, because it cannot find the `plugins` directory when imported as a package rather than run as a script.
The obvious solution to this is to change the `plugins` imports in `archiver.py` to be relative dotted imports, but this then causes `archiver.py` to fail when it is imported from the `import-mbox.py` script.
The problem is that Python [really doesn't like](https://stackoverflow.com/questions/16981921/relative-imports-in-python-3) files being used as both scripts and package modules. There have been many suggested workarounds for this over the years, with varying levels of …
> Fix imports in the scripts in tools

- tools/archiver.py
- tools/plugins/generators_old.py
This PR makes `archiver.py` more defensive when checking whether it can write to the audit log, and fixes a small issue in `generators_old.py` when a date is not available from the input message.
> Fix some small issues in tools

- tools/mappings.yaml
The ``dbid`` property of ``mbox`` objects is currently left to its default, i.e. text, but it should be keyword. This PR fixes that.
> Make dbid be a keyword

- tools/archiver.py
Mailman3 expects the `Archiver` class to have a `name` attribute corresponding to the section for the archiver in the user Mailman3 configuration file. This PR restores that attribute, setting its value to `"foal"`. If the suite is renamed Ponymail at some point then it can be changed to `"ponymail"`.
> Restore a missing name attribute for Mailman3

- server/endpoints/oauth.py
- server/plugins/messages.py
This fixes #41, and a bug where `datetime.datetime` instances were being initialised to an `int` by default.
> Fix branch and date type bugs

- tools/archiver.py
- tools/mappings.yaml
- tools/rethread.py
This PR enables extra information about threads to be stored in elastic at archival time, rather than at UI time. In other words, instead of getting information about threads dynamically when people view a Foal powered website, information about threads is added to a message as soon as it is archived.
This mode is optional, and is enabled by setting `archiver.threadinfo` to `true` in the configuration file.
This PR includes a script called `rethread.py` which can add the information to an existing database. This means that an email archive which does not currently have archival time thread properties can be updated as a whole before changing how the archiver works.
One drawback to this approach is that if messages are received out of order then this may confuse the archiver. The …
> Add thread info capabilities to the archiver

- INSTALL.md
- tools/archiver.py
- tools/mappings.yaml
- tools/plugins/elastic.py
- tools/rethread.py
Resolves #49.
This PR moves the `forum` and `size` properties to the standard Foal database entry for an archived email. The existing code for `top`, `previous`, and `thread` from #43 is retained, but improved: two new `threadparents` and `threadtimeout` properties bound the execution time of querying the new properties. The addition of these properties is optional, and is off by default. The documentation now explains their usage.
> Improve and document the thread info code

- server/endpoints/mbox.py
- server/main.py
- server/plugins/server.py
Currently, the mbox endpoint gathers up all emails and generates an mbox file before it is sent.
When you have thousands of emails, this can be several if not hundreds of megabytes that may be for nothing, if the download fails. Instead, converting it to a streaming response, where emails are fetched as chunks, will lower the memory and processing footprint of the endpoint. Should a stream fail while it is in flight, the remainder of the conversions can then safely be canceled.
> Convert mbox endpoint to a streaming response

- tools/archiver.py
This expands the way we deal with missing or ínvalid date headers, by:
- looking for an envelope From header, and if possible, using the date from there
- if no valid From envelope, search the Received headers for a useful date
- if still nothing, fall back to current time and date.
This should address #56. I've tested with emails missing all three fields (sets to NOW), the Date field only (uses the From envelope header), and missing both Date and FROM (uses Received headers then).
> Look for dates on envelope and in headers if Date is missing or invalid

- README.md
Made the nested bullet points in the Readme.md in a single form and not doubled. To avoid confusion make all the bullet points in a single * format rather than - format.
> Made Readme bullet points cleaner

- tools/import-mbox.py
Using import-mbox.py with --dedup would fail on python 3.8 due to this invalid comparison
> Fix bug causing dedup to fail when importing mailboxes

- server/endpoints/gravatar.py
This PR makes the gravatar endpoint respond with a default PNG if no gravatar can be fetched remotely. The default PNG is just the same image that gravatar uses for its default profile image.
> Use a default gravatar if one cannot be fetched

- webui/js/source/body-fixups.js
Right now the `*` in the regex to clean up quotes makes it rather slow for large quoted texts. With this change it is slightly less 'precise' but much faster, which might be a reasonable trade-off in this case?
You can reproduce at https://regexr.com/ by adding 50 or so newlines to the example input.
The effect in Pony Mail is that such emails cannot be opened at all, but produce some javascript error.
> Faster code to clean up quotes

- server/endpoints/compose.py
Follow-up on https://github.com/apache/incubator-ponymail-foal/pull/250
(draft because needs testing)
> Check all recipients against allowed domains
